// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go

// Package mock_rpc_bitcoin is a generated GoMock package.
package mock_rpc_bitcoin

import (
	context "context"
	rpc_bitcoin "nn-blockchain-api/pkg/rpc/bitcoin"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockTransactionService) CreateTransaction(ctx context.Context, utxos rpc_bitcoin.UTXO, fromAddress, toAddress string, amount int64, network string) (*string, *float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, utxos, fromAddress, toAddress, amount, network)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(*float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionServiceMockRecorder) CreateTransaction(ctx, utxos, fromAddress, toAddress, amount, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransactionService)(nil).CreateTransaction), ctx, utxos, fromAddress, toAddress, amount, network)
}

// DecodeTransaction mocks base method.
func (m *MockTransactionService) DecodeTransaction(ctx context.Context, tx, network string) (*rpc_bitcoin.DecodedTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeTransaction", ctx, tx, network)
	ret0, _ := ret[0].(*rpc_bitcoin.DecodedTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecodeTransaction indicates an expected call of DecodeTransaction.
func (mr *MockTransactionServiceMockRecorder) DecodeTransaction(ctx, tx, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeTransaction", reflect.TypeOf((*MockTransactionService)(nil).DecodeTransaction), ctx, tx, network)
}

// FundForTransaction mocks base method.
func (m *MockTransactionService) FundForTransaction(ctx context.Context, createdTx, changeAddress, network string) (string, *float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FundForTransaction", ctx, createdTx, changeAddress, network)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*float64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FundForTransaction indicates an expected call of FundForTransaction.
func (mr *MockTransactionServiceMockRecorder) FundForTransaction(ctx, createdTx, changeAddress, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FundForTransaction", reflect.TypeOf((*MockTransactionService)(nil).FundForTransaction), ctx, createdTx, changeAddress, network)
}

// SendTransaction mocks base method.
func (m *MockTransactionService) SendTransaction(ctx context.Context, signedTx, network string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, signedTx, network)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockTransactionServiceMockRecorder) SendTransaction(ctx, signedTx, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockTransactionService)(nil).SendTransaction), ctx, signedTx, network)
}

// SignTransaction mocks base method.
func (m *MockTransactionService) SignTransaction(ctx context.Context, tx, privateKey string, utxos rpc_bitcoin.UTXO, network string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignTransaction", ctx, tx, privateKey, utxos, network)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignTransaction indicates an expected call of SignTransaction.
func (mr *MockTransactionServiceMockRecorder) SignTransaction(ctx, tx, privateKey, utxos, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignTransaction", reflect.TypeOf((*MockTransactionService)(nil).SignTransaction), ctx, tx, privateKey, utxos, network)
}
