// Code generated by MockGen. DO NOT EDIT.
// Source: wallet.go

// Package mock_rpc_bitcoin is a generated GoMock package.
package mock_rpc_bitcoin

import (
	context "context"
	rpc_bitcoin "nn-blockchain-api/pkg/rpc/bitcoin"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWalletService is a mock of WalletService interface.
type MockWalletService struct {
	ctrl     *gomock.Controller
	recorder *MockWalletServiceMockRecorder
}

// MockWalletServiceMockRecorder is the mock recorder for MockWalletService.
type MockWalletServiceMockRecorder struct {
	mock *MockWalletService
}

// NewMockWalletService creates a new mock instance.
func NewMockWalletService(ctrl *gomock.Controller) *MockWalletService {
	mock := &MockWalletService{ctrl: ctrl}
	mock.recorder = &MockWalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletService) EXPECT() *MockWalletServiceMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockWalletService) CreateWallet(ctx context.Context, network string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, network)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockWalletServiceMockRecorder) CreateWallet(ctx, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockWalletService)(nil).CreateWallet), ctx, network)
}

// ImportAddress mocks base method.
func (m *MockWalletService) ImportAddress(ctx context.Context, address, walletId, network string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportAddress", ctx, address, walletId, network)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImportAddress indicates an expected call of ImportAddress.
func (mr *MockWalletServiceMockRecorder) ImportAddress(ctx, address, walletId, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportAddress", reflect.TypeOf((*MockWalletService)(nil).ImportAddress), ctx, address, walletId, network)
}

// ListUnspent mocks base method.
func (m *MockWalletService) ListUnspent(ctx context.Context, address, walletId, network string) ([]*rpc_bitcoin.Unspent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnspent", ctx, address, walletId, network)
	ret0, _ := ret[0].([]*rpc_bitcoin.Unspent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnspent indicates an expected call of ListUnspent.
func (mr *MockWalletServiceMockRecorder) ListUnspent(ctx, address, walletId, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnspent", reflect.TypeOf((*MockWalletService)(nil).ListUnspent), ctx, address, walletId, network)
}

// LoadWallet mocks base method.
func (m *MockWalletService) LoadWallet(ctx context.Context, walletId, network string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadWallet", ctx, walletId, network)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadWallet indicates an expected call of LoadWallet.
func (mr *MockWalletServiceMockRecorder) LoadWallet(ctx, walletId, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadWallet", reflect.TypeOf((*MockWalletService)(nil).LoadWallet), ctx, walletId, network)
}

// RescanWallet mocks base method.
func (m *MockWalletService) RescanWallet(ctx context.Context, walletId, network string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RescanWallet", ctx, walletId, network)
	ret0, _ := ret[0].(error)
	return ret0
}

// RescanWallet indicates an expected call of RescanWallet.
func (mr *MockWalletServiceMockRecorder) RescanWallet(ctx, walletId, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RescanWallet", reflect.TypeOf((*MockWalletService)(nil).RescanWallet), ctx, walletId, network)
}

// WalletInfo mocks base method.
func (m *MockWalletService) WalletInfo(ctx context.Context, walletId, network string) (*rpc_bitcoin.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletInfo", ctx, walletId, network)
	ret0, _ := ret[0].(*rpc_bitcoin.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WalletInfo indicates an expected call of WalletInfo.
func (mr *MockWalletServiceMockRecorder) WalletInfo(ctx, walletId, network interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletInfo", reflect.TypeOf((*MockWalletService)(nil).WalletInfo), ctx, walletId, network)
}
