// Code generated by MockGen. DO NOT EDIT.
// Source: logger.go

// Package mock_logger is a generated GoMock package.
package mock_logger

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// SetupZapLogger mocks base method.
func (m *MockLogger) SetupZapLogger() (*zap.SugaredLogger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupZapLogger")
	ret0, _ := ret[0].(*zap.SugaredLogger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupZapLogger indicates an expected call of SetupZapLogger.
func (mr *MockLoggerMockRecorder) SetupZapLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupZapLogger", reflect.TypeOf((*MockLogger)(nil).SetupZapLogger))
}
